apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskmanager-ingress

spec:
  ingressClassName: nginx

  rules:
    - host: taskmanager.local
      http:
        paths:

          # backend routes
          - path: /login
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8080

          - path: /register
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8080

          - path: /tasks
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8080

          - path: /leader
            pathType: Prefix
            backend:
              service:
                name: backend-service
                port:
                  number: 8080

          # frontend (must be last)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80